### ISSUE TITLE
String data, right truncated: value too long for type character varying(256)

### ISSUE THREAD

**Issue by UnnamedHero** [Yetangitu/owncloud-apps#12]
OC 8.1.1, PostgreSQL
Got this in my logs
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO oc_opds_metadata ("id", "updated", "date", "author", "title", "language", "publisher", "isbn", "copyright", "description", "subjects", "cover", "rescan") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)' with params [73690, "2015-08-23 19:44:52", "", "{\"\\u041a\\u0438\\u0439\\u043e\\u0441\\u0430\\u043a\\u0438 \\u0420\\u043e\\u0431\\u0435\\u0440\\u0442\":\"\\u0420\\u043e\\u0431\\u0435\\u0440\\u0442 \\u041a\\u0438\\u0439\\u043e\\u0441\\u0430\\u043a\\u0438\",\"\\u041b\\u0435\\u0447\\u0442\\u0435\\u0440 \\u0428\\u044d\\u0440\\u043e\\u043d\":\"\\u0428\\u044d\\u0440\\u043e\\u043d \\u041b\\u0435\\u0447\\u0442\\u0435\\u0440\"}", "\u0411\u043e\u0433\u0430\u0442\u044b\u0439 \u043f\u0430\u043f\u0430, \u0411\u0435\u0434\u043d\u044b\u0439 \u043f\u0430\u043f\u0430 \u0431\u043f\u0431\u043f-1", "ru", "", "", "", "", "[\"sci_business\"]", null, null]: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(256)

    /mnt/sdc/www/qqo/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 116: Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
    /mnt/sdc/www/qqo/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php - line 172: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO oc_...', Array)
    /mnt/sdc/www/qqo/lib/private/db/statementwrapper.php - line 73: Doctrine\DBAL\Statement->execute(Array)
    /mnt/sdc/www/qqo/apps/files_opds/lib/meta.php - line 123: OC_DB_StatementWrapper->execute(Array)
    /mnt/sdc/www/qqo/apps/files_opds/lib/meta.php - line 190: OCA\Files_Opds\Meta save(Array)
    /mnt/sdc/www/qqo/apps/files_opds/lib/meta.php - line 139: OCA\Files_Opds\Meta scan(73690)
    /mnt/sdc/www/qqo/apps/files_opds/lib/files.php - line 36: OCA\Files_Opds\Meta get(73690)
    /mnt/sdc/www/qqo/apps/files_opds/lib/files.php - line 58: OCA\Files_Opds\Files formatFileInfo(Object(OC\Files\FileInfo))
    /mnt/sdc/www/qqo/apps/files_opds/lib/feed.php - line 61: OCA\Files_Opds\Files formatFileInfos(Array)
    /mnt/sdc/www/qqo/apps/files_opds/index.php - line 68: OCA\Files_Opds\Feed serveFeed('/Books', 'root')
    /mnt/sdc/www/qqo/lib/private/route/route.php - line 154): runtime-created function(1) require_once('/mnt/sdc/www/qq...')
    [internal function] __lambda_func(Array)
    /mnt/sdc/www/qqo/lib/private/route/router.php - line 274: call_user_func('\x00lambda_206', Array)
    /mnt/sdc/www/qqo/lib/base.php - line 873: OC\Route\Router->match('/apps/files_opd...')
    /mnt/sdc/www/qqo/index.php - line 40: OC handleRequest()
    {main}
```

**Comment by Yetangitu** [comment]
Hmmm... long double-I guess I'll need to change those varying()s to type text and limit overflow before storing the data, that should solve it. Next release, if you want to try it for yourself just connect to the database and issue something akin to the following (assuming you have the DBPREFIX set to the standard 'oc_': 

```sql
ALTER TABLE oc_opds_metadata ALTER COLUMN author TYPE text;
```

...and see if that takes care of the problem (it should, seeing that it is the "author" column which caused the problem. This can be done on a live database without data loss, btw.

**Comment by UnnamedHero** [comment]
Yes, this workaroud has fixed my issue. Now I can view my catalog from the browser. 
Unfortunally, all my apps (FBReader, Cool Reader, Moon Reader) unable to connect to my catalog due different client issues

**Comment by Yetangitu** [comment]
All those three work for me, even Cool Reader as of OC8.1. How does this inability to connect manifest itself?

**Comment by UnnamedHero** [comment]
I have self-signied certificate on my OC instance. And Android 4.1.2 has some issiues with it, as far as I know. But yhis is not a opds_catalog problem, I think

**Comment by Yetangitu** [comment]
No, it wouldn't be. Try a free certificate from the likes of startssl.com to see whether that solves the issue, or import your own CA certificate into Android (http://wiki.cacert.org/FAQ/ImportRootCert#Android_Phones_.26_Tablets).

**Comment by UnnamedHero** [comment]
Ok... I've made huge work. 
Upgrade my device to Android 4.4.2, import my self-signed certificate  to it (thanks for the URL!!!).
MoonReader shows owncloud welcome page,  or raw xml if specify login and password in URL.
CoolReader says "Error occured while reading OPDS catalog"
FBreader says "This is not a OPDS catalog"
Aldiko show owbloaud welcome page one time, anpther times it shown emai; and password input fields and nothing more. 

This is XML from browser
```
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom"
      xmlns:dc="http://purl.org/dc/terms/"
      xmlns:dcterms="http://purl.org/dc/terms/"
      xmlns:opds="http://opds-spec.org/2010/catalog">
  <id>id:bef18817-10f9-3a90-98bf-9dc4d3508b32</id>
  <title>eem</title>
  <subtitle>eem</subtitle>
  <updated>2015-08-25T18:26:53+00:00</updated>
  <author>
    <name>eem</name>
  </author>

  <link rel="start"   
        href="?id=root"
        type="application/atom+xml;profile=opds-catalog;kind=navigation"/>
  <link rel="self"    
        href="?id=root"
        type="application/atom+xml;profile=opds-catalog;kind=navigation"/>


  <entry>
    <title>Browse catalog</title>
    <updated>2015-08-25T18:26:53+00:00</updated>
    <content type="text">Browse the catalog in alphabetical order</content>
    <link type="application/atom+xml;profile=opds-catalog;kind=navigation"
        href="?id=directory"/>
    <id>id:by_directory</id>
  </entry>
  <entry>
    <title>eem&#039;s bookshelf</title>
    <updated>2015-08-25T18:26:53+00:00</updated>
    <content type="text">This bookshelf contains 0 books</content>
    <link type="application/atom+xml;profile=opds-catalog;kind=navigation"
        href="?id=bookshelf"/>
    <id>id:by_bookshelf</id>
  </entry>
</feed>
```

**Comment by Yetangitu** [comment]
That front page looks OK. Do the links work? If so, I suspect your Android surgery has not been completely successful.

I use OPDS Catalog on a Motorola Defy, running Android 4.4.4 (CM11). All mentioned apps work as intended. I'm using a free startssl certificate. Try to access the feed from the Android browser using https and check for any anomalies in the logs (live logcat through adb).

**Comment by UnnamedHero** [comment]
I've noticed one thing. If I provide URL to /apps/files_opds/, OC redirects me to login page. After login it redirects me to /apps/files/. After that if I change URL to /apps/files_opds/ I've been asked for login and password. 

Also I've made a test account. Please, can you test it? If you can I'll send login and password via e-mail.

**Comment by Yetangitu** [comment]
Make sure you use the correct URL as shown in the OPDS preference section (including the index.php bit) as any other URL will end up in the files app. An example of a complete URL on a system which hosts Owncloud in a subdirectory is:

```
https://example.org/owncloud/index.php/apps/files_opds/
```

When hosted in a virtual domain you just leave out the subdirectory:

```
https://owncloud.example.org/index.php/apps/files_opds/
```

You did enable OPDS for the account you used for this test I assume? Accessing the files_opds url for an account for which OPDS is disabled would also redirect you to the files app...


While I could try that test account, in reality it is hard to debug without having access to the whole system (including server logs). Nevertheless, I can have a look but don't expect miracles...

**Comment by UnnamedHero** [comment]
Yes, I always copy-paste URL from OPDS settings page. 
But for the first time I tries to access _https://MY_OC_SITE/index.php/apps/files_opds/_
OC always redirects me to login page. Perhaps, I must look into my configuration files.

**Comment by UnnamedHero** [comment]
I'm giving up.
OK... :
nginx 1.6.3
php 5.5.28

any POST/GET request to https://MY_OC_SITE/index.php/apps/files_opds/ cause 302 error and redirect me to index.php
may be I need a special rewrite rule for OPDS? my nginx config is same as at https://doc.owncloud.org/server/8.0/admin_manual/installation/nginx_configuration.html

**Comment by Yetangitu** [comment]
Can you find anything out of the ordinary (error messages, warnings, etc) in the log files (nginx error.log and wherever you have owncloud log into)? Given that SELinux is on, anything in avc.log or the audit log files?

Can you access the catalog using a browser (eg. Fennec/Firefox on Android)? What about curl from a command line:

```
# (when OC is installed in a subdirectory)
curl  -u username:password https://example.org/owncloud/index.php/apps/files_opds/?id=directory

# (OC installed in subdomain)
curl  -u username:password https://owncloud.example.org/index.php/apps/files_opds/?id=directory
```

This should dump the library root in all its XML 'glory'. If it does not, something is wrong.

That nginx config should work, at least it does here. I have another system running OC (8.1.1) on lighttpd which works fine as well.

**Comment by UnnamedHero** [comment]
Selinux log is OK.

I found CoolReader did not use login/password when requesting catalog.
```
https://MY_SITE/index.php/apps/files_opds/?id=directory
```
It gets 302 error, and redirected to index.php

access.log by NGINX
```
GET /index.php/apps/files_opds/ HTTP/1.1" 200 1311 "https://MY_SITE/i
ndex.php/apps/files_opds/" "CoolReader/3(Android)" "-"
GET /index.php/apps/files_opds//?id=directory HTTP/1.1" 302 5 "https://MY_SITE/index.php/apps/files_opds/" "CoolReader/3(Android)" "-"
GET /index.php HTTP/1.1" 200 3515 "https://MY_SITE/index.php/apps/files
_opds/" "CoolReader/3(Android)" "-"
```
Requesting by cURL is fine - it always use login/password.
Other apps do not request login\password either and always received 302 error.
I thought it can be php sessions issue.... but everything is fine. php-fpm log do not contain errors.

**Comment by Yetangitu** [comment]
What log format do you use for nginx? I don't see *any* authentication info there, not in the first line either. I also notice an extraneous "-" after the user agent string ("CoolReader/3(Android)").

Cool Reader 3.1.2-72 (latest from Fdroid) works for me as of OC8.1, both on lighttpd and nginx, using a 'real' (startssl) certificate. Before that time the extraneous slashes it inserts in the path (after files_opds/) caused it to fail (for which I sent a bug report to V.Lopatim, to which he responded but on which no action has been taken yet...) but it works now. If you have an older version installed, you might want to upgrade to this version. It might - but probably won't - make a difference given that 'other apps' don't work either.

Just for reference, this is what nginx logs for a successful access to the OPDS root by Cool Reader, after which I selected the 'browse catalog' option:

```
192.168.1.17 - username [31/Aug/2015:23:42:55 +0200] "GET /index.php/apps/files_opds/ HTTP/1.1" 200 1376 "-" "CoolReader/3(Android)"
192.168.1.17 - - [31/Aug/2015:23:42:57 +0200] "GET /index.php/apps/files_opds//?id=directory HTTP/1.1" 401 5 "https://owncloud.example.org/index.php/apps/files_opds/" "CoolReader/3(Android)"
192.168.1.17 - username [31/Aug/2015:23:42:57 +0200] "GET /index.php/apps/files_opds//?id=directory HTTP/1.1" 200 3992 "https://owncloud.example.org/index.php/apps/files_opds/" "CoolReader/3(Android)"
```

Notice that on the initial access Cool Reader does use the username/password, but it initially fails to do so on following the link. This causes the server to send a 401 to which Cool Reader correctly responds by using the username/password. In your case the server does not send a 401 but instead redirects to the start page with 302.

Maybe the authentication headers are stripped off somewhere between nginx and php-fpm? 

What does fastcgi_params (in the nginx config directory) contain?

What does the log look like when you use cURL?

**Comment by UnnamedHero** [comment]
My CoolReader version is 3.1.2-102. 
I agree with you, that authentication headers are stripped somewhere, because everything is OK with curl
```
xx.xx.xx.xx - USERNAME  [02/Sep/2015:08:28:57 +0300] "GET /index.php/apps/files_opds/?id=directory HTTP/1.1" 200 22675 "-" "curl/7.44.0" "-"
```
but with CoolReader
enter my catalog:
```
xx.xx.xx.xx - USERNAME  [02/Sep/2015:08:31:11 +0300] "GET /index.php/apps/files_opds/ HTTP/1.1" 200 1311 "https://MY_SITE/index.php/apps/files_opds/" "CoolReader/3(Android)" "-"
```
press "Browse Catalog":
```
xx.xx.xx.xx - - [02/Sep/2015:08:32:48 +0300] "GET /index.php/apps/files_opds//?id=directory HTTP/1.1" 302 5 "https://MY_SITE/index.php/apps/files_opds/" "CoolReader/3(Android)" "-"
xx.xx.xx.xx - -  [02/Sep/2015:08:32:48 +0300] "GET /index.php HTTP/1.1" 200 3515 "https://MY_SITE/index.php/apps/files_opds/" "CoolReader/3(Android)" "-"
```
You see, I've got 302... Something wrong with my configuration. I've upgraded nginx to 1.8, but I still have this problem.

fastcgi_params (as comes with nginx):
```
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;
```
my site config (as :
```
server {
listen 443 ssl spdy;
server_name MY_SITE;

charset utf-8;

ssl_certificate /usr/local/etc/nginx/conf/server.crt;
ssl_certificate_key /usr/local/etc/nginx/conf/server.key;

add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
add_header X-Content-Type-Options nosniff;
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block";
add_header X-Robots-Tag none;

# Path to the root of your installation
root /mnt/sdc/www/qqo/;
# set max upload size
client_max_body_size 16G;
fastcgi_buffers 64 4K;

# Disable gzip to avoid the removal of the ETag header
gzip off;

# Uncomment if your server is build with the ngx_pagespeed module
# This module is currently not supported.
#pagespeed off;
rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;

index index.php;
error_page 403 /core/templates/403.php;
error_page 404 /core/templates/404.php;

location = /robots.txt {
allow all;
log_not_found off;
access_log off;
}

location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README){
deny all;
}

location / {
 # The following 2 rules are only needed with webfinger
rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
 rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
 rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;

rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;

 try_files $uri $uri/ /index.php;
}
location ~ \.php(?:$|/) {
fastcgi_split_path_info ^(.+\.php)(/.+)$;
include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param PATH_INFO $fastcgi_path_info;
fastcgi_param HTTPS on;
fastcgi_pass php-handler;
fastcgi_param MOD_X_ACCEL_REDIRECT_ENABLED on;
fastcgi_param modHeadersAvailable true;
}

location ^~ /data  {
internal;
#location ~ ^/data/[^/]+/files/(.+)$ {
    alias /mnt/sdc/www/qqodata/;
#    }
}

 # Optional: set long EXPIRES header on static assets
location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
 expires 30d;
# Optional: Don't log access to assets
 access_log off;
}
```

**Comment by UnnamedHero** [comment]
Oh shi~
Many bytes were downloaded, many logs and instuctions were read. Even I've upgraded to php 5.6 and nginx 1.8. Everything was useless.
And then I just reinstall opds_catalog.
And it just work. 
Man! I'm very sorry for wasting your time!

**Comment by Yetangitu** [comment]
Well, it works, and that's what matters...
