### ISSUE TITLE
Connect using Kindle web-browser?

### ISSUE THREAD

**Issue by Panderine** [Yetangitu/owncloud-apps#14]
Kindle devices are NOT OPDS compatible, but they have a web browser that can be use to download books from your own online library. Several tools exists for this (COPS, calibre content server, etc). Does this oc app enable web browsing of the catalog or only OPDS format?

**Comment by Yetangitu** [comment]
OPDS Catalog, true to its name, only provides OPDS support. HOWEVER... Owncloud/Nextcloud already provide the capability to download files through the Files app. Just point your browser there, navigate to the library root and download to your heart's content...
