### ISSUE TITLE
XML Error

### ISSUE THREAD

**Issue by stormsh** [Yetangitu/owncloud-apps#15]
Hi, after I updated to oc 9.0.1 I get an xml error. I skipped 9.0.0 because of its flaws, so I don't know if this problem occurs because of the 9.0.0 or the 9.0.1 ...

First I thought it might be a problem with php7 but when I change back to php 5.5.9 the problem is still there.

[quote]XML-Verarbeitungsfehler: Nicht übereinstimmendes Tag. Erwartet: </link>.
Adresse: https://mydomain.de/apps/files_opds/
Zeile Nr. 88, Spalte 8:[/quote]

oc 9.0.1
opds 0.6.15
php 7.0.5

thx 4 f1.
st.

**Comment by stormsh** [comment]
On the personal is a wrong link to the catalog. It looks like this https://mydomain.de//apps/files_opds/
The index.php part is missing but when I add it, I get nearly the same error, the 88 changes to 89.
What ever that means. And I found another error:

> Content Security Policy: Die Direktive 'frame-src'  should not be used. Please use Direktive 'child-src' instead.

Hope it helps.

**Comment by Yetangitu** [comment]
Do you still have this problem?

**Comment by Yetangitu** [comment]
Closing due to lack of info
