### ISSUE TITLE
Bookshelf contains no books

### ISSUE THREAD

**Issue by ma-ver-ick** [Yetangitu/owncloud-apps#16]
Hi!

I'm having owncloud 9.0.2 and opds 0.6.15. I tried opds since 0.6.10 but could never get it to show up any books. I've pointed it to the calibre library and that library contains two books for testing. Even after rescheduling a bookscan there is no book in the feed. There is also no debug message from opds in the owncloud log.
Is there anything I can do to debug this issue efficiently?

Thanks!

**Comment by Yetangitu** [comment]
The personal bookshelf will show the books you've downloaded through OPDS Catalog, ie. it will be empty until you downloaded some books by browsing the catalog (the first link) and downloading some books. OPDS Catalog does not do any background scanning, when you tell it to schedule a scan it will try to get metadata from the book file(s) and the 'net the next time you browse the catalog.

So, point your OPDS client at the catalog, use 'browse catalog' to find a publication and download it. If you want to download the same publication on another device - a phone, a tablet, a PC, your neighbour's PC or whatever - you'll find it as the first entry on the personal bookshelf. This makes it easier to keep track of which books you're using at the moment, something which can be handy when a) the library is very large and b) you access it through more than one device.

**Comment by ma-ver-ick** [comment]
I'm using kybook and browsing the catalog shows "This folder is empty". If I'm using the link in the personal page (/apps/files_opds/) with "?id=bookshelf" or "?id=directory" i'm getting an empty XML file 

`<feed xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/terms/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:opds="http://opds-spec.org/2010/catalog">
<id>XXX</id>
<title>XXX</title>
<subtitle>ownCloud OPDS catalog</subtitle>
<updated>2016-05-15T11:14:10+00:00</updated>
<author>
<name>XXX</name>
</author>
<link rel="start" href="?id=root" type="application/atom+xml;profile=opds-catalog;kind=navigation"/>
<link rel="self" href="?id=2" type="application/atom+xml;profile=opds-catalog;kind=navigation"/>
</feed>`

The only error I could find was

Undefined variable: type at /var/www/homepage/owncloud-9.0.2/apps/files_opds/index.php#77

in the Logfile.

**Comment by Yetangitu** [comment]
Is your library directory configured correctly? Can you see the books/publications from the Files app?

**Comment by Yetangitu** [comment]
also, did you enter anything in the 'supported extensions' field in the personal preference page? Try to empty that field if it seems to contain anything, even if it is only a space character.

**Comment by ma-ver-ick** [comment]
I can see my epub files in the files app. When I remove/empty the 'supported extensions' field I get the two authors that are in my library, but I'm unable to go into these directories via the opods url (/apps/files_opds/) or with kybooks. If I enter the url with the ?id=XXXX I get the same page again as with id=directory. The same with kybooks, I go to "Browser Catalog", select an author and get the list of authors again.
The library folder is maintained by calibre and contains two authors with two valid epub files. 

When I set the "supported extensions" field back to "epub" (the file extension of my files) I again get nothing at all.

**Comment by Yetangitu** [comment]
Are the files readable by the web server? Are the files correctly named? Do you see anything out of the ordinary in the web server error log?

While testing, please keep the 'supported extensions' field blank, as this could be one of the sources of these problems.

**Comment by Yetangitu** [comment]
Also, can you download the files through the Files app? OPDS Catalog uses the Files app API, so if Files can not access a file, neither can OPDS Catalog.

**Comment by ma-ver-ick** [comment]
The files are readable by the webserver, there are previews shown in the files app when navigating through the calibre library. Also I'm able to download the epub files via the files app.
I can see nothing in the php-fpm error logs, nginx error logs or else :(

**Comment by ma-ver-ick** [comment]
I know some PHP, could you point me to interessting points in the code? I would like to insert a few echo's to debug this problem myself. (Although I have no owncloud app experience yet)

**Comment by ayamshanov** [comment]
Hello,

I have got same issue; I fixed problem, try too: https://github.com/Yetangitu/owncloud-apps/pull/20

**Comment by Yetangitu** [comment]
Just merged the pull request (thanks), closing this issue for now.
