### ISSUE TITLE
XML error after deleting an epub file from Library

### ISSUE THREAD

**Issue by daita** [Yetangitu/owncloud-apps#23]
If you add a book to the shelf and then delete it from the cloud, you'll have an XML error.
You need to reset the bookshelf if you want to browse the library again.

Reproduce: 
1. Add a random ebook to the root of the library.
2. Browse the opds from a client and open the book
3. Delete the file from the cloud
4. Browse again the opds.

Using Nextcloud 10 RC1

**Comment by Yetangitu** [comment]
I'll need to add a file removal hook to get those entries out of the bookshelf. For now, just don't delete any files...

**Comment by Yetangitu** [comment]
Fixed in next version which will be published 'real soon now'
