### ISSUE TITLE
Opening files_opds fails with OCP\App not found PHP error

### ISSUE THREAD

**Issue by oc33** [Yetangitu/owncloud-apps#24]
I have own cloud 9.1.1 installed with files_opds 0.6.16. When navigating to `https://<server>/oc/apps/files_opds`, I only get an empty page and the server log shows the following error message:

```
PHP Fatal error:  Class 'OCP\App' not found in <WWWPATH>/oc/apps/files_opds/index.php on line 15
```

The last time I worked with OPDS was in the spring, then under 9.0.1, and I believe it worked then. Is this a bug or have I configured something incorrectly?

**Comment by Yetangitu** [comment]
Looks like a problem with your Owncloud installation, \OCP\App is part of the app framework which comes with Owncloud.
