### ISSUE TITLE
[Feature Request] Supported formats: FB2

### ISSUE THREAD

**Issue by trefmanic** [Yetangitu/owncloud-apps#26]
It would be nice if this app parsed fb2 files. Currently I have my whole library in fb2, because it's a very portable format. Even if metadata extraction would be only supported from an .opf file and not from .fb2 directly, that still would be fine,

**Comment by Yetangitu** [comment]
I'll look into this next time I find some time to give OPDS Catalog some dearly needed TLC.

**Comment by Yetangitu** [comment]
BTW, OPDS Catalog already supports metadata from metadata.opf files, have you tried this? It expects a directory structure like that used (and generated) by Calibre, with a single metadata.opf file in the same directory as the file to be scanned. It also supports using cover images if the .opf file contains a pointer to an existing image in the same directory.

Is this sufficient for your purposes? While it is theoretically possible to add an FB2 parser to the metadata extractor (which already contains PDF and EPUB parsers) I'd like to keep OPDS Catalog as light as feasible.

**Comment by Yetangitu** [comment]
I implemented a basic FB2 parser to extract metadata based on the [FB2 XSD](http://www.fictionbook.org/index.php/Eng:XML_Schema_Fictionbook_2.1). Problem is, I don't have any publications in the FB2 format so I can not test it. Can you send me a few documents which you deem to be representative (i.e. documents with a full set of metadata).

**Comment by trefmanic** [comment]
Hello. I've moved on to [COPS](https://github.com/seblucas/cops) for now, but here's a link to the Google Drive folder: https://drive.google.com/open?id=0B8m0cgkuMMYVS3kxUTFwYW1FX00
There's two formats for each book, EPUB and FB2 with the identical metadata.

**Comment by Yetangitu** [comment]
FictionBook 2 (.fb2) metadata support (including preview) is supported from v0.8.0.
