### ISSUE TITLE
Support for nextcloud

### ISSUE THREAD

**Issue by voidzero** [Yetangitu/owncloud-apps#27]
Hello developer, Yetangitu,

Do you plan to support Nextcloud, please?

Thank you

**Comment by guddl** [comment]
Would be nice :-)

**Comment by Yetangitu** [comment]
Yes, I do, I just need to get some time to work on these apps.

**Comment by Yetangitu** [comment]
(I'll move to NC myself one of these days)

**Comment by voidzero** [comment]
That's great. Looking forward to it :-)

**Comment by Yetangitu** [comment]
I just published files_opds (v0.7.0) and files_reader (v0.8.0) on the Nextcloud app store, please give these new releases a try.

**Comment by Yetangitu** [comment]
https://apps.nextcloud.com/apps/files_reader

https://apps.nextcloud.com/apps/files_opds
