### ISSUE TITLE
[Feature Request] Comic book format | CBR-reader

### ISSUE THREAD

**Issue by Sanookmakmak** [Yetangitu/owncloud-apps#28]
That would be nice.
Thank you!

**Comment by Yetangitu** [comment]
I'm looking into supporting more formats, CBR and CBZ being some of the potential candidates. Given the 'special' nature of these formats I might end up making a separate app for them.

**Comment by Yetangitu** [comment]
CBR and CBZ are supported since v1.0.0 (https://github.com/Yetangitu/owncloud-apps/commit/93d48d5529c6c61c9123e2c3d434044e19d504f8)
