### ISSUE TITLE
Make OPDS-catalog work with nextcloud two-factor auth

### ISSUE THREAD

**Issue by Zigulle** [Yetangitu/owncloud-apps#29]
Hello,

it is not possible to use the opds-catalog with nextclouds two-factor auth. 
When I disable the two-factor-auth, everything works fine, but after enabling it, both, Marvin on iOS an KyBook on iOS are show only an empty catalog.

It is also not possible to use an app-passwort to access the catalog.

Greetings 
Daniel

**Comment by Yetangitu** [comment]
Currently OPDS Catalog uses basic auth only, I'll check what it takes to add this NC-specific feature.

**Comment by wahlis** [comment]
I have the same issue. Please support the app passwords in Nextcloud.

**Comment by Yetangitu** [comment]
It looks like I'll have to rewrite OPDS Catalog to use to the app framework to support this, or at least like that is the most future-proof way to do it. Currently OPDS Catalog forces basic auth (in Util::authenticateUser) as that is what OPDS clients support. This no longer works when 2FA is enabled, nor does the regular checkPassword() call support app passwords.

**Comment by Yetangitu** [comment]
App passwords and 2FA are supported as of v0.8.2, 0edb3e0a596a9f2657f8233bff6cc1069c971a49

2FA is supported in Nextcloud, app passwords in Nextcloud and Owncloud.

**Comment by wahlis** [comment]
Works perfectly! Thank you for a very quick fix.

**Comment by Zigulle** [comment]
Perfect, thanx for your great work!!!
