### ISSUE TITLE
Fatal error: Call to a member function t() on null in personal.php

### ISSUE THREAD

**Issue by gpaumier** [Yetangitu/owncloud-apps#3]
Greetings,

First of all, thank you for creating this app. I was going through the OPDS documentation thinking I'd have to write the app myself when I found out you had already done it :) I'm not sure yet if your app will meet my use case, but I'm trying to find out.

Unfortunately, I got a fatal error as soon as I enabled it: When trying to open the "Personal" page:
> Fatal error: Call to a member function t() on null in /(redacted)/apps/files_opds/personal.php on line 21 

* App version: 0.5.4 downloaded today from https://apps.owncloud.com/content/show.php?content=168132
* ownCloud version: 7.0.4

I don't have debug enabled at the moment, but I found the following entries in the log:

> * Error   PHP Call to a member function t() on null at /(redacted)/apps/files_opds/personal.php#21   2015-01-04T03:51:10+00:00
> * Error   PHP Cannot redeclare class OC\Preview\Epub at /(redacted)/apps/files_opds/lib/epub-preview.php#47  2015-01-04T03:50:54+00:00
> * Fatal   core    Invalid OCS content returned for app files_opds

Please let me know if I'm doing anything wrong or if I can help further with debugging.

**Comment by Yetangitu** [comment]
Strange, it 'works for me'. Seems that $l (for 'localisation') sometimes is, and sometimes is not defined. It is now defined explicitly in personal.php as well.

Fixed in the repo.

**Comment by Yetangitu** [comment]
PS: what is your use case for OPDS support? As far as I can see, OPDS catalog does what it should - mirror a directory in OPDS, adding metadata when possible. It could do more (eg. show metadata in Owncloud file view, make metadata editable, provide search capabilities, provide fragmented views, etc), and I might add some of these features when needed and given time. Or someone else might...?

**Comment by gpaumier** [comment]
Thank you so much! The error is gone, and I can now see the catalog feed in the browser, and set up the catalog in an Android app. This is great!

However, the catalog contains no books (I have a few dozen books in this test folder). I've noticed this error on the page, I don't know if it's the cause: 
> An exception occurred while executing &#039;INSERT INTO oc_opds_metadata (`id`, `updated`, `date`, `author`, `title`, `language`, `publisher`, `isbn`, `copyright`, `description`, `subjects`, `rescan`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)&#039;:

> SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: &#039;2015-01-04T18:49:23+00:00&#039; for column &#039;updated&#039; at row 1

Am I doing something wrong? Should I put this in another issue?

If it's any use, I've taken a cursory look at the opds table in the ownCloud database, and it's empty. `updated` and `rescan` are null.

(P.S.: My use case is the following: I have a Calibre library with tons of metadata & covers, and I'd like to use the OPDS catalog app to make it available to my devices, but I don't know if the OPDS app looks at the existing `metadata.opf` and `cover.jpg` files already provided by Calibre. I would like to avoid duplication.)

Thank you for your help! I appreciate it.

**Comment by Yetangitu** [comment]
Which PHP version do you use?

**Comment by gpaumier** [comment]
Thank you for the response; I use PHP 5.6.1.

**Comment by Yetangitu** [comment]
Does it show anything interesting in the server log?

**Comment by Yetangitu** [comment]
For what concerns metadata, OPDS catalog does not look at any .opf files or covers. It tries to extract metadata from the files and uses Owncloud's thumbnail generator for covers. I don't use Calibre myself so OPDS catalog is ignorant of any Calibre-related info.

**Comment by Yetangitu** [comment]
As to why I don't use Calibre: it can not cope with large collections. It has its own peculiar way of organising publications which does not mix well with manually organised collections. It is an either-or situation, either you use Calibre or you don't. I use parts of Calibre (eg. ebook-convert) for some tasks, but I do the organising myself.

**Comment by gpaumier** [comment]
There is nothing new in the apache log, so no luck there :(

Would you be open to having an option in the OPDS catalog app to support Calibre's metadata and covers, or would you prefer I fork it to do it separately?

**Comment by Yetangitu** [comment]
Fine by me to use Calibre metadata/cover information. This can be added as another metadata source. Covers are different as OPDS catalog currently uses the Owncloud thumbnail generator and the accompanying cache support. Adding support for different cover sources would mean adding code to either circumvent the thumbnail generatorby pushing data to the cache, or querying the database for alternative covers. This is doable, but OPDS catalog currently does not support it.

**Comment by Yetangitu** [comment]
Which database do you use?

**Comment by Yetangitu** [comment]
Could you give me an example of a directory containing a single book, including metadata as produced by Calibre? I'd like to have access to a complete example (book, full metadata, cover, in the directory structure Calibre produces) to see how this can be integrated into OPDS catalog.

**Comment by gpaumier** [comment]
MySQL version: 10.0.13-MariaDB. I'm opening a separate issue for Calibre compatibility :)
