### ISSUE TITLE
OPDS catalog: Undefined type in files_opds/index.php

### ISSUE THREAD

**Issue by AS-dh** [Yetangitu/owncloud-apps#30]
OPDS catalog 0.8.2
In the nextcloud Admin log I see entries like:
   Error  Undefined variable: type at /www/htdocs/.../nextcloud/apps/files_opds/index.php#67
which seem to correlate with accessing the catalog from FBreader.
The app works Ok as far as I can tell and I'm able to access the catalog and download books...

**Comment by Yetangitu** [comment]
Fixed in [0.8.3](https://github.com/Yetangitu/owncloud-apps/blob/master/dist/files_reader-0.8.3.tar.gz?raw=true)
