### ISSUE TITLE
OPDS catalog does not work with TOTP plugin (nextcloud 11.x)

### ISSUE THREAD

**Issue by cy8aer** [Yetangitu/owncloud-apps#33]
The OPDS catalog does not work with nextcloud when TOTP is enabled. It does not work with application passwords either

**Comment by Yetangitu** [comment]
It should work, make sure you use the latest version. It works here, on NC 11 and 12, both with and without TOTP and/or app passwords. It works on OC (9.1+) as well.

**Comment by cy8aer** [comment]
Oh boy, I used the wrong password. Sorry.
