### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Psychodogg** [Yetangitu/owncloud-apps#35]
Upgraded to the 1.0 release and started getting Internal Server Error

Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: *.*.*.*
Request ID: 5AUu4jsq3YppODwfZ9TS

**Comment by Psychodogg** [comment]
I have tried uninstalling and reinstalling the 1.0.0 app and errors still happen.
Installed 0.8.4 and issue is gone and I am able to read my eBooks again.

**Comment by Yetangitu** [comment]
Which version of Nextcloud/Owncloud are you using? What does the OC/NC log file say, anything in the webserver error log?

**Comment by TheNomad11** [comment]
I have the same problem with the new version. Newest NC on Ubuntu 16.04

Here is the NC log:

OCP\Files\NotFoundException: /lk/files/webdav/Documents/file.epub

    /var/www/html/nextcloud/lib/private/Files/Node/Folder.php - line 122: OC\Files\Node\Root->get('/lk/files/w...')
    /var/www/html/nextcloud/apps/files_reader/lib/Controller/PageController.php - line 132: OC\Files\Node\Folder->get('webdav/Document...')
    /var/www/html/nextcloud/apps/files_reader/lib/Controller/PageController.php - line 87: OCA\Files_Reader\Controller\PageController->getFileInfo('/nextcloud/remo...')
    [internal function] OCA\Files_Reader\Controller\PageController->showReader()
    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_Reader\Controller\PageController), 'showReader')
    /var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_Reader\Controller\PageController), 'showReader')
    /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Files_Reade...', 'showReader', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/html/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/html/nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/files_rea...')
    /var/www/html/nextcloud/index.php - line 40: OC handleRequest()
    {main}

**Comment by Yetangitu** [comment]
OK, I'll look into it asap. Works here, on NC 11 and as far as I know 12 (git) but I did not update that 12 for a while. It seems it can not download the file, strange.

**Comment by adocampo** [comment]
I've updated today and I also have the same error...

**Comment by Yetangitu** [comment]
OK, I'm beginning to get an inkling of why it works for some, but not for others. All of you who have problems have NC/OC hosted on a subdirectory in a domain I assume (e.g. example.org/nextcloud) ? All those for whom it works have it hosted on a subdomain (e.g. nextcloud.example.org)?

Ill put out a fix asap, the problem seems to be in the request parsing code. It only it were easier to get hold of the fileId for a file none of that code would be necessary in the first place...

**Comment by 4oo4** [comment]
@Yetangitu Yeah, that's the case with me, I'm hosting my nextcloud with a path of /nextcloud on my primary domain and getting the error. Thanks for the quick fix!

**Comment by adocampo** [comment]
I also have nextcloud as subdirectory (and does not work)

**Comment by Yetangitu** [comment]
Fixed in d6026ad0a00f17c93acbe22fca0e17428928dd52, problem was due to the way Reader munged the request to, eventually, get at something which could be used to get a fileId.

**Comment by TheNomad11** [comment]
Perfect, thanks a lot!

**Comment by adocampo** [comment]
I confirm it works again 👍

**Comment by Yetangitu** [comment]
Good, more fixes coming up one of these days 'though they're not as pressing as they don't keep the thing from working.

**Comment by Psychodogg** [comment]
Sorry i had a busy weekend, yes my install it in sub dir and your fix worked great. I can now read comics with no issues. Thanks for all your hard work.
