### ISSUE TITLE
ReferenceError: getUrlParameter is not defined when trying to open Epub/cbz in Palemoon.

### ISSUE THREAD

**Issue by e-alfred** [Yetangitu/owncloud-apps#38]
Hello,

if I try to open an Epub or cbz file, I can only see a white page and the hidden controls on the top. In the error console, I get this error message shown:

ReferenceError: getUrlParameter is not defined ready.js:5:12

The browser is Palemoon 27.1.2.

**Comment by Yetangitu** [comment]
Are you running the latest version? That function is defined in `js/ready.js:105` and should be 'hoisted' up by the JS engine. It Palemooon does not, Palemoon has problems.

As a temporary solution you can try to move it up in the file so it sits at the beginning, or even move it out of the `onreadystatechange()` function. A modified version is attached to this post, try it (after removing the '.txt' extension which I had to add to be allowed to attach it).

[ready.js.txt](https://github.com/Yetangitu/owncloud-apps/files/868154/ready.js.txt)

**Comment by e-alfred** [comment]
I updated to 27.2.1 and the problem still existed. Then I used your ready.js file, but additionally I had to move renderCBR and renderEPUB to the top as well. Now both *.ebub and *.cbr files are rendered flawlessly using Palemoon.

Also I like the fact that Comic books are now rendered with this awesome app. It helps me to deprecate another unmaintained plugin I used for this purpose that I got to run on OC 9 with some heavy tweaking.

**Comment by Yetangitu** [comment]
Still... strange that it did not work with those functions in the position they are in the distribution. It *should* work, but it doesn't. Palemoon is based on Gecko - which they call Goanna - and Gecko knows how to hoist functions. I'll download Palemoon and see what's up.

**Comment by Yetangitu** [comment]
OK, just downloaded Palemoon (27.2.1/Linux) and confirmed it does not hoist those functions, a clear bug on the side of Palemoon - and a strange one.. I'll move the declarations down one level in the next release, this does work in Palemoon.

**Comment by Yetangitu** [comment]
The next (upcoming) version will contain this fix, but it also contains a new version of the bitjs unarchiver which happens to use ES6 classes... which are not supported by Palemoon...

This is a pity as that new version of bitjs brings much needed compatibility improvements with CBR. Since Palemoon does not seem to be on the verge of supporting ES6 I'm afraid you'll have to use a different browser for accessing Reader, at least until they've decided to move to a more up-to-date JS engine (see https://github.com/MoonchildProductions/Pale-Moon/issues/978 for some context on this)

**Comment by e-alfred** [comment]
Hello,

updated to 1.0.4, and now I am getting this error in the console:

`ReferenceError: bitjs is not defined cbr.js:76:8`

**Comment by Yetangitu** [comment]
Yes, unfortunately this is the case. The newer bitjs uses classes, I checked whether it was feasible to 'de-classify' the code but decided the effort was not worth the small gain. The new version of bitjs has much improved RAR-support and as such deals with the loading problems Reader had with some CBR archives. You can rip out the new bitjs and replace it with the version used in earlier versions and maintain a fork for Palemoon-users. You will not get the better RAR-support that way, but lackluster support is better than no support at all...

Or... you use another browser for Reader. Annoying, I agree, but the problems you encounter with Reader will not be the end of what you'll have to cope with when using a browser which does not support 'fashionable' JS-features.

**Comment by e-alfred** [comment]
This is fixed with Pale Moon 28 which is based on the new UXP platform (which is a fork of Firefox ESR 52).
