### ISSUE TITLE
The update broke the install

### ISSUE THREAD

**Issue by joebobtechie** [Yetangitu/owncloud-apps#39]
Detailed logs
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_reader_bookmarks (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id VARCHAR(64) DEFAULT '' NOT NULL, file_id BIGINT UNSIGNED NOT NULL, type VARCHAR(32) DEFAULT '' NOT NULL, name VARCHAR(512) DEFAULT '' NOT NULL, value VARCHAR(512) DEFAULT '' NOT NULL, content VARCHAR(4096) DEFAULT NULL, last_modified BIGINT UNSIGNED DEFAULT 0, INDEX reader_bookmarks_file_id_index (file_id), INDEX reader_bookmarks_user_id_index (user_id), INDEX reader_bookmarks_name_index (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.

---

Is there a way to uninstall the app, when you can't get to the admin page? The failed update has locked me out.

**Comment by Yetangitu** [comment]
This is a known problem with MySQL:

https://github.com/nextcloud/server/issues/2831

More on the solution can be read here:

https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html#mariadb-support

You can easily disable apps:

 * from the command line by running `occ app:disable name_of_app`
 * by removing the app from the `OC_ROOT/apps` directory

...but this will come back to bit you some other time so it is better to solve the original problem as described in the sites linked above.

**Comment by joebobtechie** [comment]
Thanks -- don't think I have the access to make the MySQL fixes, but removing the folder works.

**Comment by Yetangitu** [comment]
Can you run SQL as admin (that is, MySQL admin)? If you can, you should be able to fix this problem.

**Comment by Yetangitu** [comment]
https://github.com/Yetangitu/owncloud-apps/issues/42#issuecomment-291463767

Reports that `sudo -u www-data ./occ maintenance:repair` fixes the problem with MySQL/MariaDB
