### ISSUE TITLE
Error when installing app

### ISSUE THREAD

**Issue by EWouters** [Yetangitu/owncloud-apps#41]
Hi, I'd really like to use this app, however it gives me the following error when I try to install it:

```
An exception occurred while executing 'CREATE TABLE `oc_reader_bookmarks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) DEFAULT '' NOT NULL, `file_id` BIGINT UNSIGNED NOT NULL, `type` VARCHAR(32) DEFAULT '' NOT NULL, `name` VARCHAR(512) DEFAULT '' NOT NULL, `value` VARCHAR(512) DEFAULT '' NOT NULL, `content` VARCHAR(4096) DEFAULT NULL, `last_modified` BIGINT UNSIGNED DEFAULT 0, INDEX reader_bookmarks_file_id_index (`file_id`), INDEX reader_bookmarks_user_id_index (`user_id`), INDEX reader_bookmarks_name_index (`name`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
```

I use MariaDB, the latest Nextcloud 11, on Debian linux. 

I checked here and may have found the problem has to do with this:
```
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 954
Server version: 10.0.30-MariaDB-0+deb8u1 (Raspbian)

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show global variables like 'innodb_lar%';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| innodb_large_prefix | ON    |
+---------------------+-------+
1 row in set (0.02 sec)

MariaDB [(none)]> show global variables like 'innodb_fil%';
+--------------------------+-----------+
| Variable_name            | Value     |
+--------------------------+-----------+
| innodb_file_format       | Barracuda |
| innodb_file_format_check | ON        |
| innodb_file_format_max   | Antelope  |
| innodb_file_per_table    | ON        |
+--------------------------+-----------+
4 rows in set (0.01 sec)

```
Any help is appreciated!

**Comment by Yetangitu** [comment]
See https://github.com/Yetangitu/owncloud-apps/issues/39#issuecomment-289027750, specifically https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html#mariadb-support. Although you have `Barracuda` in that list, it might be the case that your database was created with an older version of MySQL/MariaDB and as such needs to be converted to `Barracuda`.

**Comment by Yetangitu** [comment]
https://github.com/Yetangitu/owncloud-apps/issues/42#issuecomment-291463767

Reports that `sudo -u www-data ./occ maintenance:repair` fixes the problem with MySQL/MariaDB

**Comment by EWouters** [comment]
Thank you for the instructions. I was able to convert my database to barracuda and I'm now able to use the app. It works great!
I did have to run the maintenance:repair command, it was included in the instructions you linked.

**Comment by Yetangitu** [comment]
Good to hear, I'll include this in the instructions if I don't manage to add it to the installlation procedure.
