### ISSUE TITLE
Exception on install (regarding ebook reader)

### ISSUE THREAD

**Issue by christiandreher** [Yetangitu/owncloud-apps#42]
**Info**

- OS: Debian 8.7
- Nextcloud: 11.0.2 (stable)
- Nextcloud error log does not give additional information (other like the displayed exception)

*Let me know if you need more information*

**Bug description**

When I try to install the ebook reader app, I will get the following exception:

**As text**

```
An exception occurred while executing 'CREATE TABLE `oc_reader_bookmarks` (`id` BIGINT 
UNSIGNED AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) DEFAULT '' NOT NULL, `file_id` 
BIGINT UNSIGNED NOT NULL, `type` VARCHAR(32) DEFAULT '' NOT NULL, `name` VARCHAR(512) 
DEFAULT '' NOT NULL, `value` VARCHAR(512) DEFAULT '' NOT NULL, `content` VARCHAR(4096) 
DEFAULT NULL, `last_modified` BIGINT UNSIGNED DEFAULT 0, INDEX 
reader_bookmarks_file_id_index (`file_id`), INDEX reader_bookmarks_user_id_index 
(`user_id`), INDEX reader_bookmarks_name_index (`name`), PRIMARY KEY(`id`)) DEFAULT 
CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': 

SQLSTATE[42000]: 

Syntax error or access violation: 1071 Specified key was too long; 
max key length is 767 bytes
```

**As screenshot**

![exception](https://cloud.githubusercontent.com/assets/13337480/24651456/2f63eb6a-192e-11e7-9921-443fc4a1269f.png)

**Comment by Yetangitu** [comment]
See https://github.com/Yetangitu/owncloud-apps/issues/39#issuecomment-289027750, specifically https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html#mariadb-support

**Comment by christiandreher** [comment]
Oh I didn't find that one while googling, I am sorry. Yes, that solved the problem indeed. You could evaluate if you could catch this exception and directly link to the solution or the issue you provided.

**Comment by Yetangitu** [comment]
I'll see if I can add it to the installation in some way.
