### ISSUE TITLE
An exception occurred while executing 'DELETE FROM `oc_reader_bookmarks`

### ISSUE THREAD

**Issue by kdslkdsaldsal** [Yetangitu/owncloud-apps#43]
Running ownCloud 9.1.4 and files_reader 1.0.1 (thats the one released at apps.owncloud.com) on MariaDB 10.1.22 and PHP 7.0.x shows the following logentries below if a user is deleting a file.

The same is also reported by another user running nextcloud 11.0.2 with MySQL 5.5 and PHP 5.6 at https://help.nextcloud.com/t/error-in-log-nach-loeschen-einer-datei/10796 so it doesn't look ownCloud / MariaDB / PHP specific.

*Edit* Another two with 1.0.3:
https://help.nextcloud.com/t/exception-mariadb-error-while-deleting-user-xxx/10887 
https://help.nextcloud.com/t/app-reader-ebook-reader-prevents-from-user-deletion/11026
when deleting a user.

Not quite sure if any additional info is needed so just let me know if there is anything missing.

Thanks

``
{"reqId":"l0NNxC8AqXcOaYGKKU2p","remoteAddr":"xxx","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\SyntaxErrorException\",\"Message\":\"An exception occurred while executing 'DELETE FROM `oc_reader_bookmarks` b WHERE b.file_id = ?' with params [22460]:\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'b WHERE b.file_id = '22460'' at line 1\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'DELETE FROM `oc...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(209): Doctrine\\\\DBAL\\\\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_reader\\\/lib\\\/Hooks.php(36): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_reader\\\/lib\\\/Hooks.php(24): OCA\\\\Files_Reader\\\\Hooks::deleteFile(Object(OC\\\\DB\\\\Connection), 22460)\\n#7 [internal function]: OCA\\\\Files_Reader\\\\Hooks::OCA\\\\Files_Reader\\\\{closure}(Object(OC\\\\Files\\\\Node\\\\File))\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Hooks\\\/EmitterTrait.php(98): call_user_func_array(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Hooks\\\/PublicEmitter.php(32): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\\\\\OC\\\\\\\\Files', 'preDelete', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(118): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\\\\\OC\\\\\\\\Files', 'preDelete', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/HookConnector.php(99): OC\\\\Files\\\\Node\\\\Root->emit('\\\\\\\\OC\\\\\\\\Files', 'preDelete', Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OC\\\\Files\\\\Node\\\\HookConnector->delete(Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1232): OC_Hook::emit('OC_Filesystem', 'delete', Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1108): OC\\\\Files\\\\View->runHooks(Array, '\\\/Folder\\\/IMG...')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(690): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/Folder\\\/IMG...', Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(333): OC\\\\Files\\\\View->unlink('\\\/Folder\\\/IMG...')\\n#17 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#18 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('Folder\\\/IMG_...')\\n#19 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#20 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#21 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#22 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#23 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#24 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#25 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":90}","level":3,"time":"2017-04-02T12:03:59+02:00","method":"DELETE","url":"\/remote.php\/webdav\/Folder\/IMG_20170329_140206571.jpg","user":"User"}
``

**Comment by Yetangitu** [comment]
I'll look into this issue asap, that is as soon as I've got an installation with MySQL. It works with PostgreSQL - at least it works here...

**Comment by kdslkdsaldsal** [comment]
Hey, thanks for your response and for looking into this. Nothing urgent IMHO as the installation is still running without any issues, even if the exception is thrown.

**Comment by kdslkdsaldsal** [comment]
Ah, when having a look at the query i really wonder if the ``b`` Table alias is needed in https://github.com/Yetangitu/owncloud-apps/blob/46f595a7078ab666029ea331123f7b58061d453f/files_reader/lib/Hooks.php#L35 and if that is causing the issue here?

**Comment by Yetangitu** [comment]
The table alias is there to satisfy the query builder, the line used in Reader is a more or less identical to the example given in the API docs:

https://doc.owncloud.org/api/classes/OCP.DB.QueryBuilder.IQueryBuilder.html#method_delete

`$qb = $conn->getQueryBuilder() ->delete('users', 'u') ->where('u.id = :user_id'); ->setParameter(':user_id', 1);`

The example says `; ->setParameter...`, I assume this to be wrong. Maybe it is partly right in  that the querybuilder can not handle chained parameters on MySQL? It worked for me on PostgreSQL but maybe things are different in MySQL/MariaDB-land? If you're in for an experiment, try to apply the following patch and test again:

```patch
diff --git a/files_reader/lib/Hooks.php b/files_reader/lib/Hooks.php
index fe28f96..2ccd1ba 100644
--- a/files_reader/lib/Hooks.php
+++ b/files_reader/lib/Hooks.php
@@ -32,21 +32,25 @@ class Hooks {
 
     protected static function deleteFile(IDBConnection $connection, $fileId) {
         $queryBuilder = $connection->getQueryBuilder();
-        $queryBuilder->delete('reader_bookmarks','b')->where('b.file_id = :file_id')->setParameter(':file_id', $fileId);
+        $queryBuilder->delete('reader_bookmarks','b')->where('b.file_id = :file_id');
+        $queryBuilder->setParameter(':file_id', $fileId);
         $queryBuilder->execute();
 
         $queryBuilder = $connection->getQueryBuilder();
-        $queryBuilder->delete('reader_preferences','p')->where('p.file_id = :file_id')->setParameter(':file_id', $fileId); 
+        $queryBuilder->delete('reader_preferences','p')->where('p.file_id = :file_id');
+        $queryBuilder->setParameter(':file_id', $fileId); 
         $queryBuilder->execute();
     }
 
     protected static function deleteUser(IDBConnection $connection, $userId) {
         $queryBuilder = $connection->getQueryBuilder();
-        $queryBuilder->delete('reader_bookmarks','b')->where('b.user_id = :user_id')->setParameter(':user_id', $userId);
+        $queryBuilder->delete('reader_bookmarks','b')->where('b.user_id = :user_id');
+        $queryBuilder->setParameter(':user_id', $userId);
         $queryBuilder->execute();
 
         $queryBuilder = $connection->getQueryBuilder();
-        $queryBuilder->delete('reader_preferences','p')->where('p.user_id = :user_id')->setParameter(':user_id', $userId); 
+        $queryBuilder->delete('reader_preferences','p')->where('p.user_id = :user_id');
+        $queryBuilder->setParameter(':user_id', $userId); 
         $queryBuilder->execute();
     }
```

**Comment by kdslkdsaldsal** [comment]
I think the example is just wrong and the semicolon shouldn't be there so i raised https://github.com/owncloud/core/issues/27566

I'm not that deep into SQL but when having another look at the query fired up by ownCloud:

``
DELETE FROM `oc_reader_bookmarks` b WHERE b.file_id = ?
``

it looks to me this is a wrong syntax and should be something like:

``
DELETE FROM `oc_reader_bookmarks` AS b WHERE b.file_id = ?
``

when having a look at e.g. https://dev.mysql.com/doc/refman/5.7/en/delete.html

Or am i wrong?

**Comment by UnMenorqui** [comment]
Thank you very much! It worked.

**Comment by kdslkdsaldsal** [comment]
@Yetangitu So i was able to test your patch. That one didn't worked and the issue is still there.

However i've tested the following patch (which removes the table alias) and now i can e.g. delete users again:

```
--- files_reader/lib/Hooks.php	2017-04-06 07:55:04.041215991 +0200
+++ files_reader/lib/Hooks.php.orig	2017-04-06 07:53:21.684577326 +0200
@@ -32,21 +32,21 @@
 
     protected static function deleteFile(IDBConnection $connection, $fileId) {
         $queryBuilder = $connection->getQueryBuilder();
-        $queryBuilder->delete('reader_bookmarks')->where('file_id = :file_id')->setParameter(':file_id', $fileId);
+        $queryBuilder->delete('reader_bookmarks','b')->where('b.file_id = :file_id')->setParameter(':file_id', $fileId);
         $queryBuilder->execute();
 
         $queryBuilder = $connection->getQueryBuilder();
-        $queryBuilder->delete('reader_preferences')->where('file_id = :file_id')->setParameter(':file_id', $fileId); 
+        $queryBuilder->delete('reader_preferences','p')->where('p.file_id = :file_id')->setParameter(':file_id', $fileId); 
         $queryBuilder->execute();
     }
 
     protected static function deleteUser(IDBConnection $connection, $userId) {
         $queryBuilder = $connection->getQueryBuilder();
-        $queryBuilder->delete('reader_bookmarks')->where('user_id = :user_id')->setParameter(':user_id', $userId);
+        $queryBuilder->delete('reader_bookmarks','b')->where('b.user_id = :user_id')->setParameter(':user_id', $userId);
         $queryBuilder->execute();
 
         $queryBuilder = $connection->getQueryBuilder();
-        $queryBuilder->delete('reader_preferences')->where('user_id = :user_id')->setParameter(':user_id', $userId); 
+        $queryBuilder->delete('reader_preferences','p')->where('p.user_id = :user_id')->setParameter(':user_id', $userId); 
         $queryBuilder->execute();
     }
```

**Comment by Yetangitu** [comment]
OK, thanks for the discovery work, I'll remove the alias from the hooks. Strange that it doesn't work with MySQL though, a combination of MySQL-weirdness and Doctrine-dogmatism leading to app builders having to modify their code to satisfy database dependencies, just what you'd think Doctrine should negate. I'll close this bug when the new version is ready so that those looking for htis information can easily find it.
