### ISSUE TITLE
NC 11 : blank page on Firefox with Aldiko for files_opds

### ISSUE THREAD

**Issue by Draky50110** [Yetangitu/owncloud-apps#49]
Hello.

I installed the plugin with Nextcloud 11.
Running Aldiko on Android 7, I add the catalog using the URL, then click on it : it opens Firefox (?), asks password (seems ok) and display a blank page on Firefox.

Did I miss something ?

**Comment by Yetangitu** [comment]
Aldiko is know to have problems with covers: https://github.com/rvolz/BicBucStriim/issues/80
Try another client (FBreader comes to mind) to see whether that works. If it does the problem lies with Aldiko, if not there is something amiss with your installation.

**Comment by Yetangitu** [comment]
Closing this now, please re-open if needed.
