### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by idevwebs** [Yetangitu/owncloud-apps#50]
Hello.

I just enabled the ebook reader app in nextcloud and got this error:

An exception occurred while executing 'CREATE TABLE `oc_reader_bookmarks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) DEFAULT '' NOT NULL, `file_id` BIGINT UNSIGNED NOT NULL, `type` VARCHAR(32) DEFAULT '' NOT NULL, `name` VARCHAR(512) DEFAULT '' NOT NULL, `value` VARCHAR(512) DEFAULT '' NOT NULL, `content` VARCHAR(4096) DEFAULT NULL, `last_modified` BIGINT UNSIGNED DEFAULT 0, INDEX reader_bookmarks_file_id_index (`file_id`), INDEX reader_bookmarks_user_id_index (`user_id`), INDEX reader_bookmarks_name_index (`name`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by Yetangitu** [comment]
This is a known problem with MySQL/MariaDB where 4-byte support hasd not been configured:

https://github.com/nextcloud/server/issues/2831

More on the solution can be read here:

https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html#mariadb-support

https://github.com/Yetangitu/owncloud-apps/issues/42#issuecomment-291463767 reports that `sudo -u www-data ./occ maintenance:repair` fixes the problem.
