### ISSUE TITLE
Nothing working

### ISSUE THREAD

**Issue by sdfg2** [Yetangitu/owncloud-apps#51]
NC 11.0.3, nginx 1.12.0, PHP 5.6.30, postgres 9.5.5

I installed the app via NC.  The settings show up in both Personal and Admin, but OPDS just links to the NC website, and there's no app in the app bar (which took me ages to figure out there should be one, you definitely need more of a help page ;) ).

No errors that I can see in any logs.

**Comment by sdfg2** [comment]
I have just upgraded to 12.0.2, still nothing working.  It could be that I've misconfigured something, but without much of a help page, I'm not sure what I've misconfigured.  Anyone else give any guidance?

**Comment by Yetangitu** [comment]
I'll look into all these issues coming weekend. Things "work for me" but it seems i'm the exception rather than the rule.

**Comment by Yetangitu** [comment]
Does _anything_ work with the latest release (0.8.7)?

**Comment by Yetangitu** [comment]
Closed due to lack of information, please respond if this issue persists.

**Comment by sdfg2** [comment]
I had troubles with NC13, but that's finally resolved.  I'm now on NC13.0.0 and 0.8.8 of this app.  No app shows on the bar, using MoonReader to access the catalogue just brings up a web portal to NC itself.  I've pointed the settings to my library (accessed by external storage of a local directory), and it says there is nothing in my library.  (Which could be why no app or OPDS shows up, because there's nothing to show?)  

I also just tried moving a single epub to a NC directory to see if it was a problem with external storage - no luck.

Still nothing showing in the logs.

**Comment by Yetangitu** [comment]
OPDS Catalog does not show on the menu as there is nothing to show, it is a service app. Did you enable OPDS Catalog for your use (it is disabled by default)?

What happens when you point a browser at the OPDS URL as shown in the settings page? It should produce a bit of XML, like so:

```xml

<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom"
      xmlns:dc="http://purl.org/dc/terms/"
      xmlns:dcterms="http://purl.org/dc/terms/"
      xmlns:opds="http://opds-spec.org/2010/catalog">
  <id>id:deadbeef-dead-beef-dead-beefdeadbeef</id>
  <title>Frank de Lange&#039;s Library</title>
  <subtitle>Example OPDS catalog</subtitle>
  <updated>2018-03-05T16:23:02+00:00</updated>
  <author>
    <name>Frank de Lange</name>
  </author>

  <link rel="start"   
        href="?id=root"
        type="application/atom+xml;profile=opds-catalog;kind=navigation"/>
  <link rel="self"    
        href="?id=5"
        type="application/atom+xml;profile=opds-catalog;kind=navigation"/>


  <entry>
    <title>Browse catalog</title>
    <updated>2018-03-05T16:23:02+00:00</updated>
    <content type="text">Browse the catalog in alphabetical order</content>
    <link type="application/atom+xml;profile=opds-catalog;kind=navigation"
        href="?id=directory"/>
    <id>id:by_directory</id>
  </entry>
  <entry>
    <title>Frank de Lange&#039;s bookshelf</title>
    <updated>2018-03-05T16:23:02+00:00</updated>
    <content type="text">This bookshelf contains 45 books</content>
    <link type="application/atom+xml;profile=opds-catalog;kind=navigation"
        href="?id=bookshelf"/>
    <id>id:by_bookshelf</id>
  </entry>
</feed>
```

**Comment by sdfg2** [comment]
I get the following xml:

`<feed xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/terms/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:opds="http://opds-spec.org/2010/catalog">
<id>id:175b3528-5d98-362a-9cc9-39044f916bec</id>
<title>Library</title>
<subtitle>Nextcloud OPDS catalog</subtitle>
<updated>2018-03-06T22:06:29+00:00</updated>
<author>
<name>sdfg</name>
</author>
<link rel="start" href="?id=root" type="application/atom+xml;profile=opds-catalog;kind=navigation"/>
<link rel="self" href="?id=2" type="application/atom+xml;profile=opds-catalog;kind=navigation"/>
<entry>
<title>Browse catalog</title>
<updated>2018-03-06T22:06:29+00:00</updated>
<content type="text">Browse the catalog in alphabetical order</content>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" href="?id=directory"/>
<id>id:by_directory</id>
</entry>
<entry>
<title>sdfg's bookshelf</title>
<updated>2018-03-06T22:06:29+00:00</updated>
<content type="text">This bookshelf contains 0 books</content>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" href="?id=bookshelf"/>
<id>id:by_bookshelf</id>
</entry>
</feed>`
