### ISSUE TITLE
Since upgrading to Debian Stretch and php7 I get an error

### ISSUE THREAD

**Issue by Luticus** [Yetangitu/owncloud-apps#52]
I recently upgraded to Debian Stretch and php7.  epubs seem to work fine but cbz and cbr give me this error:  Undefined variable: dllink at \/owncloud\/apps\/files_reader\/templates\/cbreader.php#15

Web server is Apache, and the browser is firefox, also happens in chrome/vivaldi.

Not sure if I'm missing a dependency or what, any advice?

**Comment by Yetangitu** [comment]
Yes, update to the upcoming new version and try again. Give it a day or 2 for those new versions to arrive.

**Comment by Luticus** [comment]
I'm stoked about the new version, and I'll give it a try as soon as it's ready!  This is one of my favorite apps so I'll be really happy to have a fully working version again.  Thanks for the update.
