### ISSUE TITLE
Link doesn't work for "Homepage" on apps.nextcloud.com

### ISSUE THREAD

**Issue by e-alfred** [Yetangitu/owncloud-apps#54]
Hello,

the "Homepage" link you put onto the Nextcloud app store for your app does not work because it points to https://github.com/Yetangitu/owncloud-apps/files_reader which does not work (Error 404).

It should be https://github.com/Yetangitu/owncloud-apps/tree/master/files_reader for the epub reader app.

**Comment by Yetangitu** [comment]
That link used to work but stopped working when I added a branch to the Github repo. I'll change it when I have some time to spare...

**Comment by xraMsamohT** [comment]
Still a dead link …

**Comment by Yetangitu** [comment]
Not in the upcoming release, 1.1.5.
