### ISSUE TITLE
Publish oC 9.0/9.1 reader app version to marketplace.owncloud.com?

### ISSUE THREAD

**Issue by ghost** [Yetangitu/owncloud-apps#55]
Hi,

the oC guys announced that the "old" apps.owncloud.com is now deprecated:

https://owncloud.org/blog/good-bye-apps-owncloud-com/

Even oC 9.0 and 9.1 users are advised to use the new marketplace which provides a backward compatible API. Are there any chances to get the 1.0.4 app version for oC 8/9 from:

https://apps.owncloud.com/content/show.php/Reader+%28ebook+reader%29?content=167127

published at the new marketplace as well?

Thanks in advance.

**Comment by Yetangitu** [comment]
One of these days I will... but not just yet, other things call for attention.

**Comment by Yetangitu** [comment]
I'm busy making new releases, these will show up on the new marketplace.

**Comment by Yetangitu** [comment]
I made new releases (OPDS Catalog 0.8.3, Reader 1.1.0) which have been published on the Nextcloud app store. I made an account on marketplace.owncloud.com and am now in the process of digesting the diverging app signing procedures for OC and NC. Once I got this fixed I'll publish on marketplace.owncloud.com as well, if you want to try the new version of Reader (now with PDF support) you can pull the dist file (https://github.com/Yetangitu/owncloud-apps/blob/master/dist/files_reader-1.1.0.tar.gz) and manually install the app. OPDS Catalog only had its maximum version numbers bumped for now, more changes will come at a later stage.

**Comment by Yetangitu** [comment]
New releases are now on marketplace.owncloud.com, please test and leave feedback if things don't work as intended.
