### ISSUE TITLE
no button to put books onto shelf

### ISSUE THREAD

**Issue by catalyst1987** [Yetangitu/owncloud-apps#60]
Hello,
     The documentation states the following: "Use the 'Browse catalog' link to download a book and it'll appear on the 'personal bookshelf'. "  Using NextCloud 12.0.3 and I do not see this button at all to be able to put books on the personal bookshelf.  

![image](https://user-images.githubusercontent.com/26027600/32982726-dce39c08-cc80-11e7-83c5-6df6a981307f.png)

Am I looking in the wrong place?

**Comment by onliniak** [comment]
https://help.nextcloud.com/t/trouble-configuring-files-opds/18917/2

**Comment by Yetangitu** [comment]
The 'personal bookshelf' should be compared to the night table next to your bed: it contains books you're currently reading (or at least put there to be read). Any book you download will end up in this list, in the order you downloaded them in. The purpose of this list is to enable you to easily get at books you're currently reading from multiple devices. This might sound trivial but if your library contains several hundreds of thousands of publications you'll soon see the utility of this feature...
