### ISSUE TITLE
OwnCloud 10 support ever coming?

### ISSUE THREAD

**Issue by SebJansen** [Yetangitu/owncloud-apps#65]

**Comment by tflidd** [comment]
With some luck, it still works when you push the max-version number a bit higher. Like it was done in this PR for Nextcloud:
https://github.com/Yetangitu/owncloud-apps/pull/63/files

**Comment by Yetangitu** [comment]
Yes, support (which indeed does not seem to take more than a version number bump) will come for files_reader and files_opds (you did not mention which app you meant). New versions coming up.
