### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by azfirefighter** [Yetangitu/owncloud-apps#68]
Attempted to install the current update (0.8.5) into my setup (12.0.3) and I get invalid signature errors.

Error | core | App with id files_opds has invalid signature | 2018-01-19T05:43:08-0700

Error | core | App with id files_opds has invalid signature | 2018-01-19T05:42:45-0700

**Comment by Grosskopf** [comment]
same issue here :)

**Comment by Yetangitu** [comment]
I'll release a new version to fix these problems, the thing is in flux at the moment due to my attempts at getting the same package to work in both Nextcloud as well as Owncloud.

**Comment by Yetangitu** [comment]
Try again with v1.1.3 (just released), this should fix the invalid signature.

**Comment by Yetangitu** [comment]
...and again with v1.1.4 which fixes problems with unrar.js

**Comment by azfirefighter** [comment]
Yeah, the one you just released yesterday (0.8.5) installs perfectly.
