### ISSUE TITLE
Error when updating OPDS catalog in Nextcloud

### ISSUE THREAD

**Issue by polkillas** [Yetangitu/owncloud-apps#69]
I tried to update the app in NC 12.0.4 from version 0.8.3 to 0.8.5 but I fond an error. The update is not possible, it throws a message like "App couldn't be updated", and when I tried to uninstall and reinstall the app, this error appears: "App with id files_opds has invalid signature".

**Comment by Yetangitu** [comment]
Strange and stranger, it was signed using the same script as I always use. No matter, I just uploaded a new release, v0.8.6, which hopefullly does away with these problems (it works for me)

**Comment by Yetangitu** [comment]
I assume v0.8.6 solved this issue, closing.
