### ISSUE TITLE
files_opds update frm 0.8.2 to 0.8.5 fails with invalid signature on NC12

### ISSUE THREAD

**Issue by pafcioooo** [Yetangitu/owncloud-apps#70]
While trying to upgrade the app on NC12 it fails with info "Couldn't update app.".
In the logs there in an error message "App with id files_opds has invalid signature"

**Comment by Yetangitu** [comment]
Strange and stranger, it was signed using the same script as I always use. No matter, I just uploaded a new release, v0.8.6, which hopefullly does away with these problems (it works for me)

**Comment by Yetangitu** [comment]
I assume this problem is solved by v0.8.6, closing this issue

**Comment by pafcioooo** [comment]
Yes, it works. Thanks:-)
