### ISSUE TITLE
files_reader 1.1.4 invalid signature on NC12

### ISSUE THREAD

**Issue by pafcioooo** [Yetangitu/owncloud-apps#71]
NC12 with files_reader 1.1.4 gives a message: "There were problems with the code integrity check. More information".

Security&Setup warning displays: "Some files have not passed the integrity check. Further information on how to resolve this issue can be found in our documentation. (List of invalid files… / Rescan…)"

List of invalid files displays 
"- files_reader
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
Raw output
-==========
Array
(
    [files_reader] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )
        )
)
"

**Comment by Yetangitu** [comment]
Try 1.1.5, was forced to use separate dist files for OC and NC due to the issue mentioned by @rello in https://github.com/nextcloud/server/issues/7973 above.

**Comment by pafcioooo** [comment]
1.1.5 works:-)
