### ISSUE TITLE
files_reader 1.1.5: Undefined index: title at \/var\/www\/nc_01\/nextcloud\/apps\/files_reader\/templates\/pdfreader.php#37

### ISSUE THREAD

**Issue by RainerEmrich** [Yetangitu/owncloud-apps#72]
Since at least 1.1.2 files_reader throws the following Error when opening a pdf document:
{"reqId":"drrwmnso1dv6aUImFBpm","level":3,"time":"2018-01-22T10:30:01+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxxxxxxxxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/files_reader\/?file=%2Fremote.php%2Fwebdav%2FNextcloud%2520Manual.pdf&type=application%2Fpdf","message":"Undefined index: title at \/var\/www\/nc_01\/nextcloud\/apps\/files_reader\/templates\/pdfreader.php#37","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}

**Comment by Yetangitu** [comment]
Will be fixed in 1.1.6, hopefully the last remnant of that long-winded template refactor...

**Comment by Yetangitu** [comment]
Fixed in 1.2.0
