### ISSUE TITLE
ebook reader: page not scroll to top after leaf through (prev or next)

### ISSUE THREAD

**Issue by UnnamedHero** [Yetangitu/owncloud-apps#73]
It is very annoying to scroll to the top of a page every time after swithing to next or prevoius page.

**Comment by Yetangitu** [comment]
Reader is designed for reading full pages, without scrolling. In what context do you have to scroll the page up after turning a page. Also, which renderer (Epub, PDF, CBx) does this apply to?

**Comment by UnnamedHero** [comment]
This applies to pdf renderer. A PDF page renders with a tiny font in fit-to-screen mode. It is very uncomfortable to read even on 24" monitor @ 1920x1080.

**Comment by Yetangitu** [comment]
Try the following patch:

```diff
diff --git a/files_reader/vendor/pdfjs/pdf.reader.js b/files_reader/vendor/pdfjs/pdf.reader.js
index 510d3d7..b5bc3ec 100644
--- a/files_reader/vendor/pdfjs/pdf.reader.js
+++ b/files_reader/vendor/pdfjs/pdf.reader.js
@@ -752,6 +752,7 @@ PDFJS.Reader.prototype.renderPage = function(pageNum) {
             renderTask.promise.then(
                 function pdfPageRenderCallback (something) {
                     if (reader.cancelPage[pageNum] === undefined) { 
+                        document.getElementById('viewer').scrollTo(0,0);
                         if (double_buffer)
                             ctx.drawImage(oscanvas, 0, 0);
                         if (textLayer)
```

**Comment by Yetangitu** [comment]
BTW, the following screen dump shows Reader with a double-page spread at 1920*1200. Quite readable I'd say, especially at 24".

![image](https://user-images.githubusercontent.com/2754838/35246638-acfbc7e8-ffc7-11e7-91e8-1704c800d028.png)

**Comment by Yetangitu** [comment]
This will be an option in the next release:

![image](https://user-images.githubusercontent.com/2754838/35248333-07f63c36-ffce-11e7-879e-4201eb7befb0.png)

The option will be disabled by default.
