### ISSUE TITLE
Allow selction of default pdf reader in settings/hamburger menu

### ISSUE THREAD

**Issue by e-alfred** [Yetangitu/owncloud-apps#74]
Hello,

now that you support pdf files (which is quite awesome), it would be great to be able to select which viewer should be used (either Nextcloud built in or the Ebook reader app).

**Comment by Yetangitu** [comment]
See https://github.com/nextcloud/server/issues/8105 for a proposed solution to this problem, it should really be handled in Core instead of in individual apps as the latter would lead to app turf wars fighting to the last bit of which app gets to handle which mime type.

**Comment by Yetangitu** [comment]
In v1.2.0 I implemented a temporary personal preferences section for this purpose where you can define for which file types Reader should be the default viewer:

![image](https://user-images.githubusercontent.com/2754838/35617668-208e018c-0679-11e8-801a-be2d423ead22.png)

Once https://github.com/nextcloud/server/issues/8105 and https://github.com/owncloud/core/issues/30306 have been implemented this section will be removed.

v1.2.0 will be released Real Soon Now...
