### ISSUE TITLE
Index too long for *dbprefix*reader_bookmarks table

### ISSUE THREAD

**Issue by prkcorp** [Yetangitu/owncloud-apps#77]
When installing reader app, DB update crashes on some MySQL setup due to index length limit to 767 bytes.

Setup information:
 * ownCloud  10.0.6.1 (Community)
 * FreeBSD 10.3
 * Mysql 5.6 (innodb_large_prefix enabled)

If a fix for MySQL setup is not planned, would it be possible to at least add a "requirements" section to documentation so the app is flagged as incompatible with some MySQL setup ?

Problem similar to the one fixed here https://github.com/owncloud/core/pull/28019

**Comment by Yetangitu** [comment]
See https://github.com/Yetangitu/owncloud-apps/issues/42#issuecomment-291463767 for a fix for this _MySQL_/_MariaDB_-related problem, especially the part where it tells you to run `sudo -u www-data ./occ maintenance:repair` to update tables on your current installation - it is not enough to just enable `innodb_large_prefix`
