### ISSUE TITLE
Metadata.db support

### ISSUE THREAD

**Issue by HLFH** [Yetangitu/owncloud-apps#9]
Hi,

metadata.db is a file that contains the metadata of a entire Calibre library.
metadata.opf contains metadata related to one only book. It would be quicker if your nice software could support the metadata.db generated by Calibre.

Thanks in advance,
HLFH

**Comment by Yetangitu** [comment]
This could be added as an import option (in the personal settings page). I'll have to set up Calibre with a smallish library (as it does not seem to cope with bigger libraries that well...) to try this. Does Calibre store this library in a specific place in its library folder (eg the root)?

**Comment by HLFH** [comment]
@Yetangitu It would be awesome. On ArchLinux, I'm using this command calibredb add * --with-library=/var/www/owncloud/data/HLFH/files/ebooks/ to build the metadata.db. So, by default, metadata.db is in the root of the library folder, here ebooks/. http://manual.calibre-ebook.com/cli/calibredb.html#calibredb-add

**Comment by Yetangitu** [comment]
I'll see if I can find some time to have a go at this one of these days. While it might speed up metadata gathering somewhat Owncloud will still need to scan the whole library to assign fileId's (which are used as file reference in OPDS catalog). If the library is big this can take a lot of time so it probably needs to be done in the background - something which I've thus far avoided.

**Comment by mikel392** [comment]
this would be a good option since i already add metadata to my ebooks.

**Comment by Yetangitu** [comment]
Implemented in 0.5.9

**Comment by mikel392** [comment]
nice! thanks for continuing to improve this awesome app

**Comment by Yetangitu** [comment]
OPDS Catalog is a typical example of 'scratching my itch', the ideal motivation for developing something. I just happened to see that this request was still open, 0.5.9 was released the 8th of January...

**Comment by mikel392** [comment]
lol yeah you barely have any issues open i think that's a good sign.
