### ISSUE TITLE
FBReader on  android can't connect nextcloud server

### ISSUE THREAD

**Issue by hksanduo** [Yetangitu/owncloud-apps#92]
I use FBReader on my android phone , but can't connect my nextcloud server. The FBReader can't display accout and password input boxes,but Aldiko on Android can.

**Comment by Yetangitu** [comment]
https://github.com/geometer/FBReaderJ/issues/440

**Comment by vincegre** [comment]
@hksanduo sorry for intrusion but how do you use FBReader with Nextcloud ? as I see only options for synchro with FBReader server !!

Thanks

**Comment by Yetangitu** [comment]
I did three things to get it to work, the third being optional:

1: created a non-SNI version of my NC installation for use by tools which don't understand SNI. This version runs on a different port (I chose `8443`) and uses a certificate which only contains the NC domain name. This gets around the problem of FBReader not supporting SNI.

2: went into the _Network library_ and used _Add catalogue_ (bottom of the list) to add the above OPDS link (try with and without `index.php` if FBReader complains about this not being an OPDS link)

3: (optional) added `data.fbreader.org` to the list of ad-image servers (which points to an empty site on my domain) so _fbreader.org_ does not get a ping each and every time I use the program.

**Comment by vincegre** [comment]
@Yetangitu Thanks for the details and explanation unhappy it's a no-go option for me ! I don't have any hosting without SNI so looks like I'll have to find an other reader more up-to-date :(

**Comment by Yetangitu** [comment]
Which web server do you use? You might be able to get by with using a proxy directive on the default site address, that way it should work as well.

**Comment by vincegre** [comment]
@Yetangitu thanks for the details and it could work so long it's your own webserver !! I'm using shared hosting so it's no way :( FBReader should be updated as SNI is standard technology since a while now....

**Comment by hksanduo** [comment]
@vincegre I can't use FBReader opds function to sync nextcloud opds catalogs.FBReader apk shows "couldm't connect to host x.x.x.x",but I use Aldiko apk syncs nextcloud opds successfully.
