### ISSUE TITLE
ISBN key ??

### ISSUE THREAD

**Issue by vincegre** [Yetangitu/owncloud-apps#95]
Hi

You state in documentation that you need to get an API key form ISBNd website but I see nowhere in app settings where to fill that api key ?? Did I miss something obvious ?

Thanks

Vincèn

**Comment by onliniak** [comment]
index.php/settings/admin/additional

**Comment by vincegre** [comment]
@onliniak 
![selection_003](https://user-images.githubusercontent.com/3164888/39033505-9d6bff74-4472-11e8-9f3d-fd90281d6051.png)
Checked both with my regular account and NextCloud admin account but I see no field for that !

PS: NC 13.0.1 OPDS Catalog app: 0.8.8 (installed yesterday in my NC !)
